version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test-pomelo-portal:
    build: .
    image: gridvo/test-pomelo-portal:dev
    container_name: test-pomelo-portal
    ports:
      - "3150:3150"
      - "3151:3151"
      - "3011:3011"
      - "3012:3012"
    depends_on:
     - zookeeper
     - kafka
    environment:
      ZOOKEEPER_SERVICE_HOST: zookeeper
      ZOOKEEPER_SERVICE_PORT: 2181
